# Generated by Django 2.2.6 on 2019-10-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
