# Generated by Django 2.2.6 on 2019-10-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pizza_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='image',
            new_name='imageUrl',
        ),
        migrations.AddField(
            model_name='pizza',
            name='imageAlt',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
