# Generated by Django 2.2.6 on 2019-10-19 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191019_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='image_file',
            new_name='image',
        ),
    ]
