# Generated by Django 2.2.6 on 2019-10-19 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191019_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='image',
            new_name='image_file',
        ),
    ]
